/**
 * NOTES: 
 *   - Run this Script logged as 'dcollectdb'.
 *
 *

 */
-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756
--   at:        2019-01-04 11:52:02 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE dcollectdb.dc_campaign_information (
    id                     INTEGER NOT NULL,
    bulletin_number        VARCHAR2(7),
    campaign_number        INTEGER,
    campaign_description   VARCHAR2(50),
    defect_code            VARCHAR2(5),
    create_timestamp       TIMESTAMP DEFAULT current_timestamp,
    update_timestamp       TIMESTAMP
);

ALTER TABLE dcollectdb.dc_campaign_information ADD CONSTRAINT dc_campaign_info_pk PRIMARY KEY ( id );

CREATE TABLE dcollectdb.dc_campaign_vin (
    id                 INTEGER NOT NULL,
    vin                CHAR(17),
    campaign_number    INTEGER,
    create_timestamp   TIMESTAMP DEFAULT current_timestamp,
    update_timestamp   TIMESTAMP
);

ALTER TABLE dcollectdb.dc_campaign_vin ADD CONSTRAINT dc_vcmpg_vin_pk PRIMARY KEY ( id );

CREATE TABLE dcollectdb.dc_vin_client_sale (
    vin                       CHAR(17) NOT NULL,
    dealer_number             CHAR(4),
    client_name               VARCHAR2(15),
    client_last_name          VARCHAR2(20),
    client_second_last_name   VARCHAR2(30),
    sale_date                 NUMBER(7),
    pdi_provider_date         NUMBER(7),
    model_id                  VARCHAR2(10),
    create_timestamp          TIMESTAMP DEFAULT current_timestamp,
    update_timestamp          TIMESTAMP
);

ALTER TABLE dcollectdb.dc_vin_client_sale ADD CONSTRAINT dc_vin_client_sale_pk PRIMARY KEY ( vin );

CREATE TABLE dcollectdb.dc_vin_master (
    vin                  CHAR(17) NOT NULL,
    model_id             VARCHAR2(10),
    japan_color_code     VARCHAR2(11),
    dealer_number        CHAR(6),
    vin_status_code      CHAR(4),
    model_year           CHAR(4),
    warranty_date        INTEGER,
    customer_sale_date   INTEGER,
    pdi_provider_date    INTEGER,
    create_timestamp     TIMESTAMP DEFAULT current_timestamp,
    update_timestamp     TIMESTAMP
);

ALTER TABLE dcollectdb.dc_vin_master ADD CONSTRAINT dc_vin_master_pk PRIMARY KEY ( vin );

CREATE TABLE dcollectdb.dc_vin_model (
    id                     INTEGER NOT NULL,
    model_year             CHAR(4),
    model_id               VARCHAR2(10),
    body_type_code         VARCHAR2(2),
    model_type_code        VARCHAR2(2),
    model_description      VARCHAR2(12),
    model_release_date     VARCHAR2(4),
    door_quantity          SMALLINT,
    adjust_body_type_id    VARCHAR2(7),
    abr_transmision_type   VARCHAR2(3),
    years_of_warranty      SMALLINT,
    km_of_warranty         INTEGER,
    prefix_engine_group    VARCHAR2(5),
    vin_position_1         CHAR(3),
    initials_distributor   VARCHAR2(5),
    distributor_number     INTEGER,
    vin_position_10        CHAR(1),
    vin_position_10_desc   CHAR(4),
    vin_pos_3_model_id     CHAR(3),
    cost_center            CHAR(3),
    accounting_account     VARCHAR2(7),
    product                VARCHAR2(5),
    create_timestamp       TIMESTAMP DEFAULT current_timestamp,
    update_timestamp       TIMESTAMP
);

ALTER TABLE dcollectdb.dc_vin_model ADD CONSTRAINT dc_vin_mdl_pk PRIMARY KEY ( id );

CREATE TABLE dcollectdb.dc_visit_vin (
    id                 INTEGER NOT NULL,
    vin                CHAR(17),
    dealer_number      INTEGER,
    create_timestamp   TIMESTAMP DEFAULT current_timestamp,
    update_timestamp   TIMESTAMP
);

ALTER TABLE dcollectdb.dc_visit_vin ADD CONSTRAINT dc_visit_vins_pk PRIMARY KEY ( id );

CREATE TABLE dcollectdb.dc_warranty_claim (
    id                       INTEGER
        CONSTRAINT nnc_dc_cpgn_info_id NOT NULL,
    vin                      VARCHAR2(7),
    dealer_number            INTEGER,
    defect_code              VARCHAR2(5),
    claim_number             VARCHAR2(6),
    miliage                  INTEGER,
    claim_status             CHAR(1),
    claim_order_start_date   INTEGER,
    claim_order_end_date     INTEGER,
    claim_received_date      INTEGER,
    period_number            INTEGER,
    workforce_refunded       NUMBER(9,2),
    parts_refunded           NUMBER(10,2),
    maintenance_refunded     NUMBER(7,2),
    total_refunded           NUMBER(7,2),
    unit_price_material1     NUMBER(10,2),
    unit_price_material2     NUMBER(10,2),
    unit_price_material3     NUMBER(10,2),
    modifcation_user_id      INTEGER,
    create_timestamp         TIMESTAMP DEFAULT current_timestamp,
    update_timestamp         TIMESTAMP
);

ALTER TABLE dcollectdb.dc_warranty_claim ADD CONSTRAINT dc_campaign_informationv1_pk PRIMARY KEY ( id );

CREATE SEQUENCE dcollectdb.dc_cpgn_info_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER dcollectdb.dc_cpgn_info_id_trg BEFORE
    INSERT ON dcollectdb.dc_campaign_information
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := dcollectdb.dc_cpgn_info_id_seq.nextval;
END;


CREATE SEQUENCE dcollectdb.dc_cmpg_vin_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER dcollectdb.dc_cmpg_vin_id_trg BEFORE
    INSERT ON dcollectdb.dc_campaign_vin
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := dcollectdb.dc_cmpg_vin_id_seq.nextval;
END;


CREATE SEQUENCE dcollectdb.dc_vinmdl_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER dcollectdb.dc_vinmdl_id_trg BEFORE
    INSERT ON dcollectdb.dc_vin_model
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := dcollectdb.dc_vinmdl_id_seq.nextval;
END;


CREATE SEQUENCE dcollectdb.dc_visvin_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER dcollectdb.dc_visvin_id_trg BEFORE
    INSERT ON dcollectdb.dc_visit_vin
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := dcollectdb.dc_visvin_id_seq.nextval;
END;


CREATE SEQUENCE dcollectdb.dc_wrr_clms_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER dcollectdb.dc_wrr_clms_id_trg BEFORE
    INSERT ON dcollectdb.dc_warranty_claim
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := dcollectdb.dc_wrr_clms_id_seq.nextval;
END;


CREATE OR REPLACE TRIGGER dcollectdb.dc_cpgn_info_upd_trg BEFORE
    UPDATE ON dcollectdb.dc_campaign_information
    FOR EACH ROW
BEGIN
    SELECT
        SYSDATE
    INTO :new.update_timestamp
    FROM
        sys.dual;

END;

CREATE OR REPLACE TRIGGER dcollectdb.dc_cmpg_vin_upd_trg BEFORE
    UPDATE ON dcollectdb.dc_campaign_vin
    FOR EACH ROW
BEGIN
    SELECT
        SYSDATE
    INTO :new.update_timestamp
    FROM
        sys.dual;

END;

CREATE OR REPLACE TRIGGER dcollectdb.dc_vin_clt_sl_upd_trg BEFORE
    UPDATE ON dcollectdb.dc_vin_client_sale
    FOR EACH ROW
BEGIN
    SELECT
        SYSDATE
    INTO :new.update_timestamp
    FROM
        sys.dual;

END;

CREATE OR REPLACE TRIGGER dcollectdb.dc_vin_mst_upd_trg BEFORE
    UPDATE ON dcollectdb.dc_vin_master
    FOR EACH ROW
BEGIN
    SELECT
        SYSDATE
    INTO :new.update_timestamp
    FROM
        sys.dual;

END;

CREATE OR REPLACE TRIGGER dcollectdb.dc_vinmdl_upd_trg BEFORE
    UPDATE ON dcollectdb.dc_vin_model
    FOR EACH ROW
BEGIN
    SELECT
        SYSDATE
    INTO :new.update_timestamp
    FROM
        sys.dual;

END;

CREATE OR REPLACE TRIGGER dcollectdb.dc_visvin_upd_trg BEFORE
    UPDATE ON dcollectdb.dc_visit_vin
    FOR EACH ROW
BEGIN
    SELECT
        SYSDATE
    INTO :new.update_timestamp
    FROM
        sys.dual;

END;

CREATE OR REPLACE TRIGGER dcollectdb.dc_wrr_clms_upd_trg BEFORE
    UPDATE ON dcollectdb.dc_warranty_claim
    FOR EACH ROW
BEGIN
    SELECT
        SYSDATE
    INTO :new.update_timestamp
    FROM
        sys.dual;

END;




/*
* ===========================================================================
* FROM HERE
* MANUALLY CREATED SCRIPTS
*/

--- grant privileges on tables to adm user
GRANT ALL PRIVILEGES ON dcollectdb.dc_campaign_information to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_campaign_vin to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_vin_client_sale to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_vin_master to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_vin_model to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_visit_vin to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_warranty_claim to dcollectadm;

--- grant privileges on sequences to adm user
GRANT ALL PRIVILEGES ON dcollectdb.dc_cpgn_info_id_seq to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_cmpg_vin_id_seq to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_vinmdl_id_seq to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_visvin_id_seq to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_wrr_clms_id_seq to dcollectadm;