ALTER TABLE DCOLLECTDB.DC_CONTACT ADD MOTHER_LAST_NAME VARCHAR2(50 CHAR);
ALTER TABLE DCOLLECTDB.DC_CONTACT MODIFY FIRST_NAME VARCHAR2(100) NOT NULL;
ALTER TABLE DCOLLECTDB.DC_CONTACT MODIFY LAST_NAME VARCHAR2(100) NOT NULL;
ALTER TABLE DCOLLECTDB.DC_CONTACT MODIFY MOTHER_LAST_NAME VARCHAR2(50) NOT NULL;