/* 
 * Honda de Mexico 2018
 * All rights reserved
 */

/**
 * NOTES: 
 *   - Run this Script logged as 'dcollectdb'.
 *
 *
 */

-- Generated by Oracle SQL Developer Data Modeler 17.3.0.261.1529
--   at:        2018-08-17 13:04:44 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

ALTER TABLE dcollectdb.dc_contact DROP CONSTRAINT DCCTC_UN1 ;