-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756
--   at:        2019-02-14 13:40:10 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g


/**
 * NOTES: 
 *   - Run this Script logged as 'dcollectdb'.
 */


CREATE TABLE dcollectdb.dc_facility_x_dealer (
    dc_facility_id   INTEGER
        CONSTRAINT nnc_facxdel_facility_id NOT NULL,
    dc_dealer_id     INTEGER
        CONSTRAINT nnc_facxdel_dealer_id NOT NULL,
    quantity         SMALLINT
);

ALTER TABLE dcollectdb.dc_facility_x_dealer ADD CONSTRAINT dc_facility_x_dealer_pk PRIMARY KEY ( dc_facility_id,
                                                                                                 dc_dealer_id );

ALTER TABLE dcollectdb.dc_facility_x_dealer
    ADD CONSTRAINT dc_deal_fk FOREIGN KEY ( dc_dealer_id )
        REFERENCES dcollectdb.dc_dealer ( id );

ALTER TABLE dcollectdb.dc_facility_x_dealer
    ADD CONSTRAINT dc_fac_fk FOREIGN KEY ( dc_facility_id )
        REFERENCES dcollectdb.dc_facility ( id );


/*
* ===========================================================================
* FROM HERE
* MANUALLY CREATED SCRIPTS
*/

--- grant privileges on tables to adm user
GRANT ALL PRIVILEGES ON dcollectdb.dc_facility_x_dealer to dcollectadm;
