/**
 * insert default model in DC_MODEL table
 * Author:  VJC80496
 * Created: July 05, 2019
 */

INSERT INTO DCOLLECTDB.DC_MODEL
(CODE, NAME, DESCRIPTION, DC_RECORD_STATUS_ID, CREATE_TIMESTAMP)
SELECT 'NA', 'NA', 'NOT ASSIGNED', (SELECT ID FROM DC_RECORD_STATUS WHERE NAME = 'enabled'), CURRENT_TIMESTAMP
FROM dual 
WHERE NOT EXISTS (SELECT * 
                 FROM DCOLLECTDB.DC_MODEL 
                 WHERE (CODE ='NA'));