/* -- DROP STATEMANTS -- */
DROP TABLE dcollectdb.dc_view_access;
DROP TABLE dcollectdb.dc_view;
DROP SEQUENCE dcollectdb.dcview_id_seq;


/* CREATE TABLES */

/*-- DC_MENU --*/
CREATE TABLE dcollectdb.dc_menu_category (
    id                 INTEGER NOT NULL,
    name               VARCHAR2(50 CHAR) NOT NULL,
    z_order            SMALLINT NOT NULL,
    create_timestamp   TIMESTAMP DEFAULT current_timestamp NOT NULL,
    update_timestamp   TIMESTAMP
);

ALTER TABLE dcollectdb.dc_menu_category ADD CONSTRAINT dcmencat_pk PRIMARY KEY ( id );

ALTER TABLE dcollectdb.dc_menu_category ADD CONSTRAINT dcmencat_order_uk UNIQUE ( z_order );

CREATE SEQUENCE dcollectdb.dcmencat_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER dcollectdb.dcmencat_seq_trg BEFORE
    INSERT ON dcollectdb.dc_menu_category
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := dcollectdb.dcmencat_id_seq.nextval;
END;

/*-- DC_VIEW --*/
CREATE TABLE dcollectdb.dc_view (
    id                 INTEGER NOT NULL,
    name               VARCHAR2(50 CHAR) NOT NULL,
    friendly_name      VARCHAR2(50 CHAR) NOT NULL,
    route              VARCHAR2(255 CHAR) NOT NULL,
    z_order            SMALLINT NOT NULL,
    dc_menu_category_id INTEGER NOT NULL,
    create_timestamp   TIMESTAMP DEFAULT current_timestamp NOT NULL,
    update_timestamp   TIMESTAMP
);

ALTER TABLE dcollectdb.dc_view ADD CONSTRAINT dciew_pk PRIMARY KEY ( id );

ALTER TABLE dcollectdb.dc_view ADD CONSTRAINT dcview_name_uk UNIQUE ( name );

ALTER TABLE dcollectdb.dc_view ADD CONSTRAINT dcview_order_uk UNIQUE ( z_order );

ALTER TABLE dcollectdb.dc_view
    ADD CONSTRAINT dcview_dcmencat_fk FOREIGN KEY ( dc_menu_category_id )
        REFERENCES dcollectdb.dc_menu_category ( id );

CREATE SEQUENCE dcollectdb.dcview_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER dcollectdb.dcview_id_seq_trg BEFORE
    INSERT ON dcollectdb.dc_view
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := dcollectdb.dcview_id_seq.nextval;
END;

/*-- DC_VIEW_ACTION --*/
CREATE TABLE dcollectdb.dc_view_action (
    id                 INTEGER NOT NULL,
    short_name         VARCHAR2(50 CHAR) NOT NULL,
    friendly_name      VARCHAR2(50 CHAR) NOT NULL,
    dc_view_id         INTEGER NOT NULL,
    create_timestamp   TIMESTAMP DEFAULT current_timestamp NOT NULL,
    update_timestamp   TIMESTAMP
);

ALTER TABLE dcollectdb.dc_view_action ADD CONSTRAINT dcvact_pk PRIMARY KEY ( id );

ALTER TABLE dcollectdb.dc_view_action
    ADD CONSTRAINT dcvact_dcview_fk FOREIGN KEY ( dc_view_id )
        REFERENCES dcollectdb.dc_view ( id );

CREATE SEQUENCE dcollectdb.dcvact_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER dcollectdb.dcvact_id_seq_trg BEFORE
    INSERT ON dcollectdb.dc_view_action
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := dcollectdb.dcvact_id_seq.nextval;
END;

/*-- DC_VACTION_X_ROLE --*/
CREATE TABLE dcollectdb.dc_vaction_x_role (
    dc_role_id          INTEGER NOT NULL,
    dc_view_action_id   INTEGER NOT NULL
);

ALTER TABLE dcollectdb.dc_vaction_x_role ADD CONSTRAINT dcactr_pk PRIMARY KEY ( dc_view_action_id, dc_role_id );

ALTER TABLE dcollectdb.dc_vaction_x_role
    ADD CONSTRAINT dcactr_dcvact_fk FOREIGN KEY ( dc_view_action_id )
        REFERENCES dcollectdb.dc_view_action ( id );

ALTER TABLE dcollectdb.dc_vaction_x_role
    ADD CONSTRAINT dcactrdcrole_fk FOREIGN KEY ( dc_role_id )
        REFERENCES dcollectdb.dc_role ( id );

/* MODIFY TABLES */
ALTER TABLE dcollectdb.dc_role DROP COLUMN dc_record_status_id;
ALTER TABLE dcollectdb.dc_ldap_group DROP COLUMN dc_record_status_id;

--- grant privileges on tables to adm user
GRANT ALL PRIVILEGES ON dcollectdb.dc_menu_category to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_view to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_view_action to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_vaction_x_role to dcollectadm;

--- grant privileges on sequences to adm user
GRANT ALL PRIVILEGES ON dcollectdb.dcmencat_id_seq to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dcview_id_seq to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dcvact_id_seq to dcollectadm;


/* -- DC_MENU_CATEGORY-- */
INSERT INTO DCOLLECTDB.DC_MENU_CATEGORY(NAME, Z_ORDER)VALUES('Catalogs', 1);


/* -- DC_VIEW-- */
INSERT INTO DCOLLECTDB.DC_VIEW(NAME, ROUTE, FRIENDLY_NAME, Z_ORDER, DC_MENU_CATEGORY_ID) SELECT 'terchiefs', 'terchief/list', 'Heads of territory', 1, ID FROM DC_MENU_CATEGORY WHERE NAME = 'Catalogs';
INSERT INTO DCOLLECTDB.DC_VIEW(NAME, ROUTE, FRIENDLY_NAME, Z_ORDER, DC_MENU_CATEGORY_ID) SELECT 'dealers', 'dealer/list', 'Dealers', 2, ID FROM DC_MENU_CATEGORY WHERE NAME = 'Catalogs';
INSERT INTO DCOLLECTDB.DC_VIEW(NAME, ROUTE, FRIENDLY_NAME, Z_ORDER, DC_MENU_CATEGORY_ID) SELECT 'dealergroups', 'dealergroup/list', 'Dealer groups', 3, ID FROM DC_MENU_CATEGORY WHERE NAME = 'Catalogs';
INSERT INTO DCOLLECTDB.DC_VIEW(NAME, ROUTE, FRIENDLY_NAME, Z_ORDER, DC_MENU_CATEGORY_ID) SELECT 'facilities','facility/list', 'Facilities', 4, ID FROM DC_MENU_CATEGORY WHERE NAME = 'Catalogs';
INSERT INTO DCOLLECTDB.DC_VIEW(NAME, ROUTE, FRIENDLY_NAME, Z_ORDER, DC_MENU_CATEGORY_ID) SELECT 'models', 'model/list', 'Models', 5, ID FROM DC_MENU_CATEGORY WHERE NAME = 'Catalogs';


/* -- DC_VIEW_ACTION -- */
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'view', 'View', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'terchiefs';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'create', 'Create', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'terchiefs';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'edit', 'Edit', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'terchiefs';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'change_status', 'Change Status', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'terchiefs';

INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'view', 'View', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'dealers';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'create', 'Create', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'dealers';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'edit', 'Edit', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'dealers';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'delete', 'Delete', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'dealers';

INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'view', 'View', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'dealergroups';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'create', 'Create', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'dealergroups';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'edit', 'Edit', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'dealergroups';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'delete', 'Delete', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'dealergroups';

INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'view', 'View', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'facilities';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'create', 'Create', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'facilities';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'edit', 'Edit', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'facilities';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'change_status', 'change_status', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'facilities';

INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'view', 'View', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'models';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'create', 'Create', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'models';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'edit', 'Edit', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'models';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'change_status', 'Change Status', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'models';


/* -- DC_VACTION_X_ROLE -- */
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='view' AND v.NAME='terchiefs') FROM DUAL;
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='create' AND v.NAME='terchiefs') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='edit' AND v.NAME='terchiefs') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='change_status' AND v.NAME='terchiefs') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='view' AND v.NAME='dealers') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='create' AND v.NAME='dealers') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='edit' AND v.NAME='dealers') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='delete' AND v.NAME='dealers') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='view' AND v.NAME='dealergroups') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='create' AND v.NAME='dealergroups') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='edit' AND v.NAME='dealergroups') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='delete' AND v.NAME='dealergroups') FROM DUAL;
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='view' AND v.NAME='facilities') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='create' AND v.NAME='facilities') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='edit' AND v.NAME='facilities') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='change_status' AND v.NAME='facilities') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='view' AND v.NAME='models') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='create' AND v.NAME='models') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='edit' AND v.NAME='models') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='change_status' AND v.NAME='models') FROM DUAL; 