/* -- DC_MENU_CATEGORY-- */
INSERT INTO DCOLLECTDB.DC_MENU_CATEGORY(NAME, Z_ORDER)VALUES('Security', 2);

/* -- DC_VIEW-- */
INSERT INTO DCOLLECTDB.DC_VIEW(NAME, ROUTE, FRIENDLY_NAME, Z_ORDER, DC_MENU_CATEGORY_ID) SELECT 'roles', 'role/list', 'Roles', 6, ID FROM DC_MENU_CATEGORY WHERE NAME = 'Security';

/* -- DC_VIEW_ACTION -- */
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'view', 'View', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'roles';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'create', 'Create', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'roles';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'edit', 'Edit', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'roles';
INSERT INTO DCOLLECTDB.DC_VIEW_ACTION(SHORT_NAME, FRIENDLY_NAME, DC_VIEW_ID) SELECT 'delete', 'Delete', ID FROM DCOLLECTDB.DC_VIEW WHERE NAME = 'roles';

/* -- DC_VACTION_X_ROLE -- */
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='view' AND v.NAME='roles') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='create' AND v.NAME='roles') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='edit' AND v.NAME='roles') FROM DUAL; 
INSERT INTO DCOLLECTDB.DC_VACTION_X_ROLE(DC_ROLE_ID, DC_VIEW_ACTION_ID) SELECT (SELECT r.ID FROM DCOLLECTDB.DC_ROLE r WHERE r.NAME = 'ADMIN') AS ROLE_ID, (SELECT va.ID FROM DCOLLECTDB.DC_VIEW_ACTION va JOIN DCOLLECTDB.DC_VIEW v ON va.DC_VIEW_ID=v.ID WHERE va.SHORT_NAME='delete' AND v.NAME='roles') FROM DUAL;