/* -- CHANGE TABLE DC_LDAP_GROUP -- */
ALTER TABLE DCOLLECTDB.DC_LDAP_GROUP
DROP CONSTRAINT LDGRP_UN1;

ALTER TABLE DCOLLECTDB.DC_LDAP_GROUP
ADD CONSTRAINT LDGRP_ID_UNI UNIQUE (LDAP_ID);

ALTER TABLE DCOLLECTDB.DC_LDAP_GROUP 
MODIFY NAME VARCHAR2( 50 ) NOT NULL;

ALTER TABLE DCOLLECTDB.DC_LDAP_GROUP 
MODIFY LDAP_ID VARCHAR2( 25 ) NOT NULL;