CREATE TABLE dcollectdb.dc_service_type (
    id  INTEGER,
    name VARCHAR2(100 CHAR) NOT NULL,
    dc_record_status_id INTEGER CONSTRAINT nnc_dcservice_dc_record_statu NOT NULL,
    create_timestamp TIMESTAMP DEFAULT current_timestamp CONSTRAINT nnc_dcservice_create_timestam NOT NULL,
    update_timestamp TIMESTAMP,
	CONSTRAINT dc_service_pk PRIMARY KEY ( id ),
	CONSTRAINT dc_service_status_fk1 FOREIGN KEY(dc_record_status_id)
        REFERENCES dcollectdb.dc_record_status( id )
);

ALTER TABLE dcollectdb.dc_service_type ADD CONSTRAINT unique_service_type UNIQUE ( name );

CREATE SEQUENCE dc_service_type_seq START WITH 1;

CREATE OR REPLACE TRIGGER service_id_increment 
BEFORE INSERT ON dcollectdb.dc_service_type 
FOR EACH ROW
BEGIN
  SELECT dc_service_type_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;


CREATE TABLE dcollectdb.dc_service_type_x_order_type(
	dc_order_type_id INTEGER CONSTRAINT nnc_ordrtype_notnull_id NOT NULL,
	dc_service_type_id INTEGER  CONSTRAINT nnc_servicetype_notnull_id NOT NULL,
	CONSTRAINT dc_service_x_order_type_fk1 FOREIGN KEY(dc_order_type_id)
		REFERENCES dcollectdb.dc_order_type( id ),
	CONSTRAINT dc_order_type_x_service_fk1 FOREIGN KEY(dc_service_type_id)
		REFERENCES dcollectdb.dc_service_type( id )
);

ALTER TABLE dcollectdb.dc_service_type_x_order_type ADD CONSTRAINT dc_service_type_x_order_type_pk PRIMARY KEY ( dc_service_type_id,
                                                                                                   dc_order_type_id );
ALTER TABLE dcollectdb.dc_order_type DROP COLUMN service_type;

INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE (ID,NAME,DC_RECORD_STATUS_ID,CREATE_TIMESTAMP,UPDATE_TIMESTAMP) VALUES (1,'BP',1,to_timestamp('06-DEC-21 04.46.39.866000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE (ID,NAME,DC_RECORD_STATUS_ID,CREATE_TIMESTAMP,UPDATE_TIMESTAMP) VALUES (2,'SE',1,to_timestamp('06-DEC-21 04.46.40.080000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null);

INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (1,1);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (2,1);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (3,1);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (4,1);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (5,1);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (6,1);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (7,1);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (8,1);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (9,1);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (1,2);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (2,2);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (3,2);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (4,2);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (5,2);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (6,2);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (7,2);
INSERT INTO DCOLLECTDB.DC_SERVICE_TYPE_X_ORDER_TYPE (DC_ORDER_TYPE_ID,DC_SERVICE_TYPE_ID) VALUES (9,2);

GRANT ALL PRIVILEGES ON dcollectdb.dc_service_type to dcollectadm;
GRANT ALL PRIVILEGES ON dcollectdb.dc_city to dc_service_type_x_order_type;
